version: '3.9'

services:
  db:
    image: mysql:8.0.31
    ports:
      - "5432:3306"
    environment:
      MYSQL_ROOT_PASSWORD: hunter2
      MYSQL_DATABASE: phn

  php:
    extra_hosts:
      - host.docker.internal:host-gateway
    image: ghcr.io/genych/php82:latest
    ports:
      - "9000"
    volumes:
      - .:/www
    working_dir: /www
    command: sh start.sh
    depends_on:
      - db
    environment:
      - XDEBUG_MODE=debug,profile
      - APP_ENV=local
    restart: on-failure

  nginx:
    build:
      context: .docker
      dockerfile: nginx.Dockerfile
    ports:
      - "80:80"
      - "443:443"
    links:
      - php
